name: "Conventional Commits"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Message
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
            revert